// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3rVgr_9yDf6aPGay_IUQRdtZE2IOu3s',
    appId: '1:999640099005:web:6b332510f0b77c9418afd4',
    messagingSenderId: '999640099005',
    projectId: 'shopping-list-16d7b',
    authDomain: 'shopping-list-16d7b.firebaseapp.com',
    storageBucket: 'shopping-list-16d7b.firebasestorage.app',
    measurementId: 'G-FGYSD82Z4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3rVgr_9yDf6aPGay_IUQRdtZE2IOu3s',
    appId: '1:999640099005:android:98993189349c889418afd4',
    messagingSenderId: '999640099005',
    projectId: 'shopping-list-16d7b',
    storageBucket: 'shopping-list-16d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3rVgr_9yDf6aPGay_IUQRdtZE2IOu3s',
    appId: '1:999640099005:ios:b7718af67b1516b218afd4',
    messagingSenderId: '999640099005',
    projectId: 'shopping-list-16d7b',
    storageBucket: 'shopping-list-16d7b.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3rVgr_9yDf6aPGay_IUQRdtZE2IOu3s',
    appId: '1:999640099005:ios:b7718af67b1516b218afd4',
    messagingSenderId: '999640099005',
    projectId: 'shopping-list-16d7b',
    storageBucket: 'shopping-list-16d7b.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH3rVgr_9yDf6aPGay_IUQRdtZE2IOu3s',
    appId: '1:999640099005:web:665d5ef4c6fffb1c18afd4',
    messagingSenderId: '999640099005',
    projectId: 'shopping-list-16d7b',
    authDomain: 'shopping-list-16d7b.firebaseapp.com',
    storageBucket: 'shopping-list-16d7b.firebasestorage.app',
    measurementId: 'G-QK6SXNHCS5',
  );
}
